<footer>
	<div class="footer__dark">
		<div class="footer__info">
			<div class="footer__contato">
				<div class="footer__contato__itens">Endereço Avenida 7 de setembro</div>
				<div class="footer__contato__itens">(42)99871-8769</div>
				<div class="footer__contato__itens">André Vitor </div>
			</div>
			<div class="footer__social">
				<div class="footer__social__itens"><a href="http://www.facebook.com" target="_blank"><img src="arquivos/img/facebook.png">
					<p>andree_Vitor</p></a></div>
				<div class="footer__social__itens"><a href="http://www.instagram.com" target="_blank"><img src="arquivos/img/instagram.png">
					<p>andree_Vitor</p></a></div>
				<div class="footer__social__itens"><a href="http://www.twitter.com" target="_blank"><img src="arquivos/img/twitter.png">
					<p>andree_Vitor</p></a></div>
				<div class="footer__social__itens"><a href="http://www.linkedin.com" target="_blank"><img src="arquivos/img/linkedin.png">
					<p>andree_Vitor</p></a></div>
			</div>
		</div>
	</div>
	<div class="footer__dark__bottom">
	</div>
</footer>
</body>
</html>