<!DOCTYPE html>
<html>
<head>
	<title>Teste</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<link rel="stylesheet" type="text/css" href="arquivos/css/estilo.css">
	<link rel="stylesheet" type="text/css" href="arquivos/css/footer.css">
	<link rel="stylesheet" type="text/css" href="arquivos/css/header.css">
</head>
<body>
	<header>
		<div class="header__back">
			<div class="header__menu">
				<nav class="header__menu__opcoes">
					<div class="header__menu__opcoes__itens selected">Home</div>
					<div class="header__menu__opcoes__itens">Categorias</div>
					<div class="header__menu__opcoes__itens">Portifolio</div>
					<div class="header__menu__opcoes__itens">Sobre</div>
				</nav>
				<div class="clear"></div>
			</div>
			<div class="header__center">
				<div class="header__center__imagens">
				<div class="header__center__imagens__itens"><img src="arquivos/img/dragao.jpg" alt="Dragao Dragon Ball"></div>
				<div class="header__center__imagens__itens"><img src="arquivos/img/logo.png" alt="Logo Dragon Ball"></div> 
				</div>
				<div class="header__animacao__left">
					<div class="header__animacao__left__itens"><img class="header__animacao__left__img__hover" src="arquivos/img/mestre_kameat.png"><img class="header__animacao__left__img__hover" src="arquivos/img/mestre_kameat2.png"></div>
				</div>
				<div class="header__animacao__rigth">
					<div class="header__animacao__rigth__itens"><img class="header__animacao__rigth__img__hover" src="arquivos/img/picolo.png"><img class="header__animacao__rigth__img__hover" src="arquivos/img/picolo2.png"></div>
				</div>
			</div>	
		</div>
	</header>